### ISSUE TITLE
KeyError: 'arclength'

### ISSUE THREAD

**Issue by ryu-bu** [CIDARLAB/pigeon#1]
Hi, 
I am trying the this code

> 5 EX
P pLlacO1 4
= BBm 14
c tetR-lite 1
= BB 14
T T1 6
= BB 14
P lambdaPr 4
= BBm 14
c lacI-lite 1
= BB 14
T T1 6
= BB 14
P pLtetO1 4
= BBm 14
c lambdacI-lite 1
= BB 14
T T1 6
<5 SP
v pSB1A2

but I keep getting the following error message:

> Traceback (most recent call last):
  File "cmdline.py", line 40, in <module>
    main()
  File "cmdline.py", line 33, in main
    parser.parseAndGenerateImage(data)
  File "/Users/ryu/Desktop/pigeon/Pigeon.py", line 46, in parseAndGenerateImage
    start, end = dr.renderDNA(axis, design, part_renderers, regs = arcs, reg_renderers=dr.std_reg_renderers())
  File "/Users/ryu/Desktop/pigeon/dnaplotlib.py", line 3192, in renderDNA
    regs.sort(key=lambda x: x['arclength'], reverse=False)
  File "/Users/ryu/Desktop/pigeon/dnaplotlib.py", line 3192, in <lambda>
    regs.sort(key=lambda x: x['arclength'], reverse=False)
KeyError: 'arclength'

The code works with http://pigeon.synbiotools.org/ . 
Could you fix this error? This is for the integration with Raven. Thanks.

**Comment by rkrishnasanka** [comment]
Okay, I fixed this to some extent in 2e52e1e6b03d968aa725626486f0e07852e780bd :
- I added `s` for Scars and 'v' for vectors in the grammar
- So now this doesn't throw the arc length error. The issue was based on how the grammar was dealing with the individual items here. We need to modify the grammar a bit.
